### ISSUE TITLE
Make mobile app. It kind of hard to access it from the internet without the proper http web address. 

### ISSUE THREAD

**Issue by Pakuwag** [Pakuwag/Ryori-Bon#1]
But - however - this was only meant for one person. We don't have to make it too elaborate.

**Comment by amichal** [comment]
Got it. Will try to work on it tonight

**Comment by amichal** [comment]
PR #3 added the basic PWA manifest.  Will work on iOS next.

**Comment by amichal** [comment]
Deployed at https://pakuwag.github.io/Ryori-Bon/?source=pwa
